// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBu1tqBZPSkG91N1vd0_WAh6LTrd4FVDg',
    appId: '1:663450990774:web:12a7412b75a841cb938e17',
    messagingSenderId: '663450990774',
    projectId: 'greenex-48474',
    authDomain: 'greenex-48474.firebaseapp.com',
    storageBucket: 'greenex-48474.firebasestorage.app',
    measurementId: 'G-XBY95L1KEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx3IEEpz1vjdpVtq44J4-sqMWFLd1Zw6s',
    appId: '1:663450990774:android:8aab116e76efdb96938e17',
    messagingSenderId: '663450990774',
    projectId: 'greenex-48474',
    storageBucket: 'greenex-48474.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlPwEh06S-wukK9yK_dD0bNIrfE_W62as',
    appId: '1:663450990774:ios:d602019bd5878c2f938e17',
    messagingSenderId: '663450990774',
    projectId: 'greenex-48474',
    storageBucket: 'greenex-48474.firebasestorage.app',
    iosBundleId: 'com.example.clientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlPwEh06S-wukK9yK_dD0bNIrfE_W62as',
    appId: '1:663450990774:ios:d602019bd5878c2f938e17',
    messagingSenderId: '663450990774',
    projectId: 'greenex-48474',
    storageBucket: 'greenex-48474.firebasestorage.app',
    iosBundleId: 'com.example.clientApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBu1tqBZPSkG91N1vd0_WAh6LTrd4FVDg',
    appId: '1:663450990774:web:0159dd8e3645d2e2938e17',
    messagingSenderId: '663450990774',
    projectId: 'greenex-48474',
    authDomain: 'greenex-48474.firebaseapp.com',
    storageBucket: 'greenex-48474.firebasestorage.app',
    measurementId: 'G-W83RM5G6MH',
  );
}
